FROM python:3.8

#ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y && \
#	apt-get install -y gcc python-dev libkrb5-dev && \
#	apt-get install -y python3-pip && \
	pip3 install --upgrade pip && \
#	pip3 install --upgrade virtualenv && \
#	pip3 install pywinrm[kerberos] && \
#	apt install krb5-user -y && \
#	pip3 install pywinrm && \
	pip3 install ansible && \
	apt install -y openssh-client && \
	apt install -y openssh-server && \
	apt install -y sshpass

COPY homework.yaml homework.yaml
COPY inventory inventory
COPY test.txt test.txt