FROM python:3.8

RUN apt-get update && apt-get install -y openssh-server && apt-get install -y sudo
RUN pip3 install --upgrade pip && pip3 install ansible
RUN mkdir /var/run/sshd
RUN useradd -ms /bin/bash ansible
RUN echo 'ansible:ansible' | chpasswd
RUN sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed -i 's@session\s*required\s*pam_loginuid.so@session optional pam_loginuid.so@g' /etc/pam.d/sshd

ENV NOTVISIBLE "in users profile"
RUN echo "export VISIBLE=now" >> /etc/profile

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]
