stages:
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Building"
    - mkdir build
    - touch build/info.txt
  tags:
    - netology

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Testing"
    - test build/info.txt
  tags:
    - netology
